export const menuItemsData = [
    {
      id: 1,
      name: 'Big Burger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 24,
      img: '/images/bigBurger.png',
    },
    {
      id: 2,
      name: 'Summer Asian Slaw',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 14,
      img: '/images/bowl1.png',
    },
    {
      id: 3,
      name: 'Butter Chicken ',
      info: 'spicey with Butter and cooked with perfection',
      price: 45,
      img: 'images/Butterchicken.png',
    },
    {
      id: 4,
      name: 'white sauce pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 12,
      img: '/images/bowl3.png',
    },
    {
      id: 5,
      name: 'Chicken Curry',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 45,
      img: '/images/ChickenCurry.png',
    },
    {
      id: 6,
      name: 'Chicken Biryani',
      info: 'Made with best cooked rice for crispy perfection',
      price: 40,
      img: '/images/ChickenBiryani.png',
    },
    {
      id: 7,
      name: 'Dosa',
      info: 'south indian taste Dosa with idli to enjoy your meal',
      price: 20,
      img: '/images/dosa.png',
    },
    {
      id: 8,
      name: 'Margarita Pizza',
      info: 'Best Margarita Pizza with best bread',
      price: 34,
      img: '/images/pizza.png',
    },
    {
      id: 9,
      name: 'Noodles',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 13,
      img: '/images/NoodlesStirFry.png',
    },
    {
      id: 10,
      name: 'breakfast cereal',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 20,
      img: '/images/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png',
    },
    {
      id: 11,
      name: 'Roasted Chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 50,
      img: '/images/RoastedChicken.png',
    },
    {
      id: 12,
      name: 'fried chicken',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 56,
      img: '/images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
    },
    {
      id: 13,
      name: 'Indian Style Samosas',
      info: 'spicey Indian style samosas with garlic and then deep fried to crispy perfection',
      price: 10,
      img: '/images/samosa.png',
    },
    {
      id: 14,
      name: 'hamburger',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 20,
      img: '/images/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466.png',
    },
    {
      id: 15,
      name: 'Muttor Paneer',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 40,
      img: '/images/MuttorPaneer.png',
    },
    {
      id: 16,
      name: 'Pizza Pasta',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 20,
      img: '/images/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077.png',
    },
    {
      id: 17,
      name: 'Pizza',
      info: 'spicey with garlic and then deep fried to crispy perfection',
      price: 50,
      img: '/images/pizza.png',
    },
  ];